# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=100)),
                ('job_company_name', models.CharField(max_length=200)),
                ('job_area_name', models.CharField(max_length=50)),
                ('job_salary', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('job_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_company_type', models.CharField(max_length=100)),
                ('job_publish_time', models.CharField(max_length=20)),
                ('job_address', models.CharField(max_length=100)),
                ('job_company_scale', models.CharField(max_length=100)),
                ('job_require_other', models.CharField(max_length=100)),
                ('job_description', models.TextField(blank=True)),
                ('job_position_tag', models.CharField(max_length=1000)),
                ('job_welfare', models.CharField(max_length=1000)),
                ('job_cleaned_description', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job51.Job')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentCount',
            fields=[
                ('segment_count_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.IntegerField()),
                ('key_word', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
